export const ADD_POSTIT = 'ADD_POSTIT';
export const REMOVE_POSTIT = 'REMOVE_POSTIT';
export const UPDATE_POSTIT = 'UPDATE_POSTIT';
export const UPDATE_ALL = 'UPDATE_ALL';
export const ERROR = 'ERROR';
export const SHOW_CONFIRM_DELETE_DIALOG = 'SHOW_CONFIRM_DELETE_DIALOG';
export const SET_BEING_DELETED = 'SET_BEING_DELETED';
